# groupId to be used for newly created packages
groupId: com.example

# information about parent pom
parentPom:
  # absolute path to the parent pom file
  path: /path/to/parent/pom.xml
  # the artifactId to be set for the parent pom
  artifactId: parent-pom
  # the application title to be set for the parent pom
  appTitle: Parent Pom
  # version to be set for the parent pom
  version: 1.0.0

# information required for all and analyse packages
all:
  # prefix that is to be used to set the artifactId for all and analyse packages
  artifactId: my-aem-project
  # application title
  appTitle: My AEM Project
  # version to be set for all pom
  version: 1.0.0-SNAPSHOT

# information about projects
projects:
  -
    # absolute path to the project folder
    projectPath: /path/to/my/aem/project
    # Array of relative path(s) (w.r.t. the project folder) to the existing content package(s) that needs to be restructured.
    # NOTE : only content packages are expected here, NOT bundle/jar artifacts
    existingContentPackageFolder:
      - content/ui.apps
      - content/ui.content
    # relative path (w.r.t. the existing content package folder) to the filter.xml file
    # (If not specified, default path `/src/main/content/META-INF/vault/filter.xml` will be used.)
    relativePathToExistingFilterXml: src/main/content/META-INF/vault/filter.xml
    # relative path (w.r.t. the existing content package folder) to the jcr_root directory
    # (If not specified, default path `/src/main/content/jcr_root` will be used)
    relativePathToExistingJcrRoot: src/main/content/jcr_root
    # prefix that is to be used to set the artifactId for newly created ui.apps and ui.content packages
    artifactId: my-aem-project
    # application title
    appTitle: My AEM Project
    # application ID (will be used for config and package folder names)
    appId: my-aem-project
    # project specific version to be used for content packages
    version: 1.0.0-SNAPSHOT
    # Array of relative path(s) (w.r.t. the project folder) to the existing code bundles (will be embedded in the all package).
    coreBundles:
      - target/my-aem-project.core-1.0.0-SNAPSHOT.jar
    # OSGi config folders that need to be renamed.
    # The existing/source OSGi config folder PATH (JCR path stating from '/apps') is expected as key
    # and the replacement OSGi folder NAME is expected as value.
    osgiFoldersToRename:
      /apps/my-aem-project/config.prod: config.publish.prod
      /apps/system/config.author.dev1: config.author.dev
      /apps/system/config.author.dev2: config.author.dev
      
   
	
	
	
	<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:sling="http://sling.apache.org/jcr/sling/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0"
    jcr:primaryType="nt:unstructured"
    jcr:title="System Notification"
    sling:resourceType="cq/gui/components/authoring/dialog"
    helpPath="en/cq/current/wcm/default_components.html#Image">
    <content
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/container">
        <layout
            jcr:primaryType="nt:unstructured"
            sling:resourceType="granite/ui/components/foundation/layouts/tabs"
            type="nav"/>
        <items jcr:primaryType="nt:unstructured">
            <text jcr:primaryType="nt:unstructured" jcr:title="Text" sling:resourceType="granite/ui/components/foundation/section">
                <layout jcr:primaryType="nt:unstructured" margin="{Boolean}false" sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns" />
                <items jcr:primaryType="nt:unstructured">
                    <column jcr:primaryType="nt:unstructured" sling:resourceType="granite/ui/components/foundation/container">
                        <items jcr:primaryType="nt:unstructured">
							<enabled
								jcr:primaryType="nt:unstructured"
								sling:resourceType="granite/ui/components/coral/foundation/form/switch"
								fieldLabel="Enable System Notification"
								checked="{Boolean}true"
								uncheckedValue="{Boolean}false"
								fieldDescription="If disabled, the System Notification will not be displayed on any page"
								name="./enabled"/>
                        	<headline
								jcr:primaryType="nt:unstructured"
								sling:resourceType="granite/ui/components/foundation/form/textfield"
								fieldDescription="Headline"
								fieldLabel="Headline"
								name="./headline" />
							<copytext
								jcr:primaryType="nt:unstructured"
								sling:resourceType="cq/gui/components/authoring/dialog/richtext"
								fieldLabel="Copytext"
								name="./copytext"
								useFixedInlineToolbar="{Boolean}true">
		                        <rtePlugins jcr:primaryType="nt:unstructured">
		                            <links
		                                jcr:primaryType="nt:unstructured"
		                                features="*"/>
		                        </rtePlugins>
		                        <uiSettings jcr:primaryType="nt:unstructured">
		                            <cui jcr:primaryType="nt:unstructured">
		                                <inline
		                                    jcr:primaryType="nt:unstructured"
		                                    toolbar="[links#modifylink,links#unlink,links#anchor]"/>
		                                <fullscreen
		                                    jcr:primaryType="nt:unstructured"
		                                    toolbar="[links#modifylink,links#unlink,links#anchor]"/>
		                            </cui>
		                        </uiSettings>
							</copytext>
                        </items>
                    </column>
                </items>
            </text>
            <links jcr:primaryType="nt:unstructured" jcr:title="Links" sling:resourceType="granite/ui/components/foundation/section">
                <layout jcr:primaryType="nt:unstructured" margin="{Boolean}false" sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns" />
                <items jcr:primaryType="nt:unstructured">
                    <column jcr:primaryType="nt:unstructured" sling:resourceType="granite/ui/components/foundation/container">
                        <items jcr:primaryType="nt:unstructured">
                        	<linklist
                                jcr:primaryType="nt:unstructured"
                                sling:resourceType="granite/ui/components/foundation/form/multifield"
                                class="full-width"
								eaem-nested=""
                                fieldDescription="Click 'Add' to add a new Link"
                                fieldLabel="Links">
                                <field jcr:primaryType="nt:unstructured"
									   jcr:title="Link Item"
									   sling:resourceType="granite/ui/components/foundation/form/fieldset"
									   name="./links">
                                    <layout
                                        jcr:primaryType="nt:unstructured"
                                        sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns"
                                        method="absolute"/>
                                    <items jcr:primaryType="nt:unstructured">
                                        <column
                                            jcr:primaryType="nt:unstructured"
                                            sling:resourceType="granite/ui/components/foundation/container">
                                            <items jcr:primaryType="nt:unstructured">
                                           		<linktext
                                                    jcr:primaryType="nt:unstructured"
                                                    sling:resourceType="granite/ui/components/foundation/form/textfield"
                                                    fieldDescription="Enter Link Text"
                                                    fieldLabel="Link Text"
                                                    name="./linktext" />
                                                <linktarget
                                                    jcr:primaryType="nt:unstructured"
                                                    sling:resourceType="granite/ui/components/foundation/form/pathbrowser"
                                                    fieldDescription="Select Path"
                                                    fieldLabel="Link Target"
                                                    name="./linktarget"
                                                    rootPath="/content" />
												<linkbehaviour jcr:primaryType="nt:unstructured"
												    name="./linkbehaviour"
												    fieldLabel="Link Behaviour"
												    sling:resourceType="granite/ui/components/foundation/form/select">
												    <items jcr:primaryType="nt:unstructured">
												        <samewindow jcr:primaryType="nt:unstructured"
												            text="Same Window"
												            value=""/>
												        <newwindow jcr:primaryType="nt:unstructured"
												            text="New Window"
												            value="_blank"/>
												    </items>
												</linkbehaviour>
                                            </items>
                                        </column>
                                    </items>
								</field>
							</linklist>
            			</items>
            		</column>
            	</items>
			</links>
		</items>
    </content>
</jcr:root>

	
	
	
	
	
	
	


